### ISSUE TITLE
Netlify integration

### ISSUE THREAD

**Issue by chrisfinazzo** [remy/wm#21]
As mentioned [here][], I want to use Netlify's integration to send a deploy notification (along with a tweet through Bridgy) on each post to my site. The site's webhook is as follows:

`https://webmention.app/check?token=f586a47e-92ef-4dab-9f13-498b85ca4c27&limit=1&url=https://chrisfinazzo.com/rss.xml`

However, far as I can tell, no webmention is sent when the deploy finishes. Is this using the correct form for the URL that the hook expects?

This is the site's [repo][], if that helps to figure out what's going on.

[here]: https://twitter.com/chrisfinazzo/status/1256237424038096899
[repo]: https://github.com/chrisfinazzo/blog

**Comment by remy** [comment]
It looks like these are being parsed and going out: https://webmention.app/check?url=https://chrisfinazzo.com/rss.xml

I see this as the result:

```json
{
  "urls": [
    {
      "endpoint": {
        "url": "https://micro.blog/webmention",
        "type": "webmention"
      },
      "source": "https://chrisfinazzo.com/2020/04/20/social-distancing-pt3-a-better-linkblog/",
      "target": "https://www.manton.org/2016/03/03/the-evolution-of.html"
    },
    {
      "endpoint": {
        "url": "https://scriptingosx.com/xmlrpc.php",
        "type": "pingback"
      },
      "source": "https://chrisfinazzo.com/2020/04/07/social-distancing-pt1-hello-zsh/",
      "target": "https://scriptingosx.com/2019/11/new-book-release-day-moving-to-zsh/"
    }
  ]
}
```

So that's two mentions, one to a webmentioned back endpoint and one that's a pingback. Whether they display your mention is entirely down to them, but it looks like they're being found in your source and going out to the targets.

I'm going to close this, but let me know if you think (the result) is wrong.

Just doing a quick search, there's this target that you could point to test your webmentions are actually going out: https://django-wm.dev/

**Comment by remy** [comment]
Oh darn, no - for the webmention to send it needs to be a `POST` - if you can check that (though I thought that Netlify does `POST` by default).

**Comment by chrisfinazzo** [comment]
Yeah, my one liner does send a POST request, but I'll ask in their forums if it's the default. Will update when they take a look at this

**Comment by chrisfinazzo** [comment]
While the engineer I spoke with isn't that familiar with webmentions, they did some more testing on the URL. From the forum thread:

> What I do know is that removing the &limit=1 parameter from the URL returns OK and it works just fine on https://webmention.app/test too.

🤔
